import { useEffect, useState } from "react";
import { BarChart3, FileText, Image as ImageIcon, LogOut, Mail, Save, Settings, ShieldCheck } from "lucide-react";
import "./admin.css";

type Admin = { id: number; name: string; email: string; role: string };
type Dashboard = { totals: { visits: number; contacts: number }; languages: { language: string; count: number }[]; devices: { device: string; count: number }[]; timeline: { date: string; count: number }[] };
async function api(path: string, options?: RequestInit) { const response = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json", ...(options?.headers || {}) }, ...options }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "Erreur serveur"); return response.json(); }

function Login({ onLogin }: { onLogin: (admin: Admin) => void }) { const [email, setEmail] = useState("admin@universride.net"); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { const data = await api("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); onLogin(data.admin); } catch (err) { setError(err instanceof Error ? err.message : "Connexion impossible"); } }; return <main className="admin-login"><form className="admin-login-card" onSubmit={submit}><div className="admin-brand"><ShieldCheck size={28} /><span>UNIVERS <b>RIDE</b></span></div><h1>Espace administrateur</h1><p>Connectez-vous pour gérer le site vitrine.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Mot de passe<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="admin-error">{error}</div>}<button className="button button-primary" type="submit">Se connecter</button></form></main>; }

function Dashboard({ data }: { data: Dashboard | null }) { if (!data) return <p>Chargement des statistiques…</p>; const cards = [["Visites (30 jours)", data.totals.visits], ["Messages reçus", data.totals.contacts]]; return <><div className="admin-kpi-grid">{cards.map(([label, value]) => <div className="admin-kpi" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="admin-panels"><section className="admin-panel"><h2>Trafic récent</h2><div className="bar-chart">{data.timeline.map(item => <div className="bar-col" key={item.date}><div className="bar" style={{ height: `${Math.max(8, Math.min(100, Number(item.count) * 8))}%` }} title={`${item.date}: ${item.count}`} /><small>{item.date.slice(5)}</small></div>)}</div></section><section className="admin-panel"><h2>Langues et appareils</h2><p>{data.languages.map(x => <span className="admin-chip" key={x.language}>{x.language.toUpperCase()} · {x.count}</span>)}</p><p>{data.devices.map(x => <span className="admin-chip" key={x.device}>{x.device} · {x.count}</span>)}</p></section></div></>; }

function Contacts() { const [contacts, setContacts] = useState<any[]>([]); const load = () => { void api("/api/admin/contacts").then(d => setContacts(d.contacts)); }; useEffect(() => { load(); }, []); const update = async (id: number, status: string) => { await api(`/api/admin/contacts/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); load(); }; return <section className="admin-panel"><h2>Centre de messages</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Contact</th><th>Message</th><th>Date</th><th>Statut</th></tr></thead><tbody>{contacts.map(c => <tr key={c.id}><td><b>{c.fullName}</b><br /><small>{c.email}</small></td><td>{c.message}</td><td>{new Date(c.createdAt).toLocaleDateString()}</td><td><select value={c.status} onChange={e => update(c.id, e.target.value)}><option>NEW</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>ARCHIVED</option></select></td></tr>)}</tbody></table></div></section>; }

function Content() { const [key, setKey] = useState("hero"); const [form, setForm] = useState({ titleFr: "", titleEn: "", titleSg: "", contentFr: "", contentEn: "", contentSg: "" }); const save = async () => { await api(`/api/admin/content/sections/${key}`, { method: "PUT", body: JSON.stringify(form) }); alert("Contenu enregistré"); }; return <section className="admin-panel"><h2>CMS multilingue</h2><label>Clé de section<input value={key} onChange={e => setKey(e.target.value)} /></label><div className="admin-form-grid">{(["Français", "English", "Sängö"] as const).map((language, i) => { const names = [["titleFr", "contentFr"], ["titleEn", "contentEn"], ["titleSg", "contentSg"]][i]; return <fieldset key={language}><legend>{language}</legend><input placeholder="Titre" value={form[names[0] as keyof typeof form]} onChange={e => setForm({ ...form, [names[0]]: e.target.value })} /><textarea placeholder="Contenu" rows={5} value={form[names[1] as keyof typeof form]} onChange={e => setForm({ ...form, [names[1]]: e.target.value })} /></fieldset>; })}</div><button className="button button-primary" onClick={save}><Save size={16} /> Enregistrer</button></section>; }

function SettingsPanel() { const [values, setValues] = useState({ call_center_phone: "+236 72 63 63 63", support_email: "universride.rca@univers-ride.org" }); const save = async () => { await Promise.all(Object.entries(values).map(([key, value]) => api(`/api/admin/content/settings/${key}`, { method: "PUT", body: JSON.stringify({ value }) }))); alert("Paramètres enregistrés"); }; return <section className="admin-panel"><h2>Paramètres du site</h2>{Object.entries(values).map(([key, value]) => <label key={key}>{key}<input value={value} onChange={e => setValues({ ...values, [key]: e.target.value })} /></label>)}<button className="button button-primary" onClick={save}><Save size={16} /> Enregistrer</button></section>; }

function Media() { const [items, setItems] = useState<any[]>([]); const [file, setFile] = useState<File | null>(null); const load = () => { void api("/api/admin/media").then(d => setItems(d.media)); }; useEffect(() => { load(); }, []); const upload = async () => { if (!file) return; const body = new FormData(); body.append("file", file); await fetch("/api/admin/media", { method: "POST", credentials: "include", body }); setFile(null); load(); }; const remove = async (id: number) => { await api(`/api/admin/media/${id}`, { method: "DELETE" }); load(); }; return <section className="admin-panel"><h2>Médiathèque</h2><div className="admin-upload-row"><input type="file" accept="image/*" onChange={e => setFile(e.target.files?.[0] || null)} /><button className="button button-primary" onClick={upload}>Téléverser</button></div><div className="media-grid">{items.map(item => <figure className="media-card" key={item.id}><img src={item.url} alt={item.filename} /><figcaption>{item.filename}<button onClick={() => remove(item.id)}>Supprimer</button></figcaption></figure>)}</div></section>; }

export default function AdminApp() { const [admin, setAdmin] = useState<Admin | null>(null); const [tab, setTab] = useState("dashboard"); const [dashboard, setDashboard] = useState<Dashboard | null>(null); useEffect(() => { api("/api/auth/me").then(d => setAdmin(d.admin)).catch(() => setAdmin(null)); }, []); useEffect(() => { if (admin) api("/api/admin/analytics").then(setDashboard).catch(() => {}); }, [admin]); if (!admin) return <Login onLogin={setAdmin} />; const tabs = [["dashboard", BarChart3, "Dashboard"], ["contacts", Mail, "Messages"], ["content", FileText, "CMS"], ["media", ImageIcon, "Médias"], ["settings", Settings, "Paramètres"]] as const; return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><ShieldCheck size={24} /><span>UNIVERS <b>RIDE</b></span></div><p className="admin-user">{admin.name}<small>{admin.role}</small></p>{tabs.map(([id, Icon, label]) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)}><Icon size={17} />{label}</button>)}<button className="admin-logout" onClick={() => api("/api/auth/logout", { method: "POST" }).then(() => setAdmin(null))}><LogOut size={17} />Déconnexion</button></aside><div className="admin-main"><header className="admin-topbar"><div><span className="kicker"><span className="kicker-dot" />Back-office</span><h1>{tabs.find(x => x[0] === tab)?.[2]}</h1></div><a href="/" className="button button-quiet">Voir le site</a></header>{tab === "dashboard" && <Dashboard data={dashboard} />}{tab === "contacts" && <Contacts />}{tab === "content" && <Content />}{tab === "media" && <Media />}{tab === "settings" && <SettingsPanel />}</div></main>; }
